a= int(input("Masukkan nilai ke 1 = "))
b= int(input("Masukkan nilai ke 2 = "))
c= int(input("Masukkan nilai ke 3 = "))
d= int(input("Masukkan nilai ke 4 = "))
e= int(input("Masukkan nilai ke 5 = "))
rata= ((a+b+c+d+e)/5)
print ("Hasil rata-rata adalah =",rata)
